name: 'Gemini Code Assist Review'
description: 'Runs the Gemini code assist review'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  gemini_api_key:
    description: 'Gemini API key'
    required: true
runs:
  using: "composite"
  steps:
    - run: pip install google-generativeai requests
      shell: bash
    - run: python ${{ github.action_path }}/../../scripts/gemini_pr_review.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
